name: Build

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.x"
          source-url: https://nuget.pkg.github.com/mihainegrisan/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore dependencies
        run: dotnet restore MFO.PartnerManagementService.sln

      - name: Build
        run: dotnet build MFO.PartnerManagementService.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test MFO.PartnerManagementService.sln --no-build --configuration Release --verbosity normal
